language: objective-c
osx_image: xcode9.1

env:
   global:
   - LANG=en_US.UTF-8

   - PROJECT="FireMock.xcodeproj"
   - IOS_SCHEME="FireMock"
   - IOS_SDK=iphonesimulator11.0

   matrix:
   - DESTINATION="OS=10.0,name=iPhone 8" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" POD_LINT="YES"
   - DESTINATION="OS=10.1,name=iPhone X"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" POD_LINT="NO"
   - DESTINATION="OS=10.2,name=iPhone 7" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" POD_LINT="NO"

script:
- set -o pipefail

- if [ $POD_LINT == "YES" ]; then
      pod lib lint;
  fi
